# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexe/Prog/Home-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexe/Prog/Home-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexe/Prog/Home-Server/CMakeFiles /home/alexe/Prog/Home-Server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexe/Prog/Home-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server.out

# Build rule for target.
server.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server.out
.PHONY : server.out

# fast build rule for target.
server.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/build
.PHONY : server.out/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/server/client.o: src/server/client.cpp.o
.PHONY : src/server/client.o

# target to build an object file
src/server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/client.cpp.o
.PHONY : src/server/client.cpp.o

src/server/client.i: src/server/client.cpp.i
.PHONY : src/server/client.i

# target to preprocess a source file
src/server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/client.cpp.i
.PHONY : src/server/client.cpp.i

src/server/client.s: src/server/client.cpp.s
.PHONY : src/server/client.s

# target to generate assembly for a file
src/server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/client.cpp.s
.PHONY : src/server/client.cpp.s

src/server/reqres.o: src/server/reqres.cpp.o
.PHONY : src/server/reqres.o

# target to build an object file
src/server/reqres.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/reqres.cpp.o
.PHONY : src/server/reqres.cpp.o

src/server/reqres.i: src/server/reqres.cpp.i
.PHONY : src/server/reqres.i

# target to preprocess a source file
src/server/reqres.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/reqres.cpp.i
.PHONY : src/server/reqres.cpp.i

src/server/reqres.s: src/server/reqres.cpp.s
.PHONY : src/server/reqres.s

# target to generate assembly for a file
src/server/reqres.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/reqres.cpp.s
.PHONY : src/server/reqres.cpp.s

src/server/router.o: src/server/router.cpp.o
.PHONY : src/server/router.o

# target to build an object file
src/server/router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/router.cpp.o
.PHONY : src/server/router.cpp.o

src/server/router.i: src/server/router.cpp.i
.PHONY : src/server/router.i

# target to preprocess a source file
src/server/router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/router.cpp.i
.PHONY : src/server/router.cpp.i

src/server/router.s: src/server/router.cpp.s
.PHONY : src/server/router.s

# target to generate assembly for a file
src/server/router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/router.cpp.s
.PHONY : src/server/router.cpp.s

src/server/server.o: src/server/server.cpp.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/server.cpp.o
.PHONY : src/server/server.cpp.o

src/server/server.i: src/server/server.cpp.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/server.cpp.i
.PHONY : src/server/server.cpp.i

src/server/server.s: src/server/server.cpp.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/server/server.cpp.s
.PHONY : src/server/server.cpp.s

src/test/request.o: src/test/request.cpp.o
.PHONY : src/test/request.o

# target to build an object file
src/test/request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/request.cpp.o
.PHONY : src/test/request.cpp.o

src/test/request.i: src/test/request.cpp.i
.PHONY : src/test/request.i

# target to preprocess a source file
src/test/request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/request.cpp.i
.PHONY : src/test/request.cpp.i

src/test/request.s: src/test/request.cpp.s
.PHONY : src/test/request.s

# target to generate assembly for a file
src/test/request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/request.cpp.s
.PHONY : src/test/request.cpp.s

src/test/router.o: src/test/router.cpp.o
.PHONY : src/test/router.o

# target to build an object file
src/test/router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/router.cpp.o
.PHONY : src/test/router.cpp.o

src/test/router.i: src/test/router.cpp.i
.PHONY : src/test/router.i

# target to preprocess a source file
src/test/router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/router.cpp.i
.PHONY : src/test/router.cpp.i

src/test/router.s: src/test/router.cpp.s
.PHONY : src/test/router.s

# target to generate assembly for a file
src/test/router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/router.cpp.s
.PHONY : src/test/router.cpp.s

src/test/stream.o: src/test/stream.cpp.o
.PHONY : src/test/stream.o

# target to build an object file
src/test/stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/stream.cpp.o
.PHONY : src/test/stream.cpp.o

src/test/stream.i: src/test/stream.cpp.i
.PHONY : src/test/stream.i

# target to preprocess a source file
src/test/stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/stream.cpp.i
.PHONY : src/test/stream.cpp.i

src/test/stream.s: src/test/stream.cpp.s
.PHONY : src/test/stream.s

# target to generate assembly for a file
src/test/stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/test/stream.cpp.s
.PHONY : src/test/stream.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server.out"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server/client.o"
	@echo "... src/server/client.i"
	@echo "... src/server/client.s"
	@echo "... src/server/reqres.o"
	@echo "... src/server/reqres.i"
	@echo "... src/server/reqres.s"
	@echo "... src/server/router.o"
	@echo "... src/server/router.i"
	@echo "... src/server/router.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/test/request.o"
	@echo "... src/test/request.i"
	@echo "... src/test/request.s"
	@echo "... src/test/router.o"
	@echo "... src/test/router.i"
	@echo "... src/test/router.s"
	@echo "... src/test/stream.o"
	@echo "... src/test/stream.i"
	@echo "... src/test/stream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

